Fix unresolved symbol for `PyObject_Vectorcall` on PyPy 3.9 and up.
