Restore `_PyLong_NumBits` on Python 3.13 and later
